services:
  - type: web
    name: checotype
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash -c 'alembic upgrade head && gunicorn app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: checotype-db
          property: connectionString
      - key: AUTO_CREATE_DB
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: checotype-db
    plan: free
